local: false
window:
  width: 750
  height: 750
  fps: 30
buttons:
  classic:
    width: 300
    height: 50
  images:
    width: 100
    height: 100
games:
  1: Rummy
backgrounds:
  count: 12
cards:
  types:
    1: ace
    2: two
    3: three
    4: four
    5: five
    6: six
    7: seven
    8: eight
    9: nine
    10: ten
    11: jack
    12: queen
    13: king
  suits:
    1: spades
    2: hearts
    3: clubs
    4: diamonds
  backs: [castle_back_01, castle_back_02]
  width: 69
  height: 94
  spacing: 20


