local: false
debug: false
window:
  width: 750
  height: 750
  fps: 60
  name: Cards
buttons:
  classic:
    width: 300
    height: 50
  images:
    width: 100
    height: 100
font:
  family: Times
  size: 30
games:
  1: Rummy
  2: Golf
backgrounds:
  count: 12
  route: assets/backgrounds/
  extension: .png
cards:
  types:
    1: ace
    2: two
    3: three
    4: four
    5: five
    6: six
    7: seven
    8: eight
    9: nine
    10: ten
    11: jack
    12: queen
    13: king
  suits:
    1: spades
    2: hearts
    3: clubs
    4: diamonds
  backs:
    cross_hatch:
      frames: 1
      animation_speed: 0
    pipes:
      frames: 1
      animation_speed: 0
    black_plants:
      frames: 1
      animation_speed: 0
    blue_plants:
      frames: 1
      animation_speed: 0
    three_fish:
      frames: 1
      animation_speed: 0
    four_fish:
      frames: 1
      animation_speed: 0
    rose:
      frames: 1
      animation_speed: 0
    shell:
      frames: 1
      animation_speed: 0
    castle:
      frames: 2
      animation_speed: 20
    robot:
      frames: 3
      animation_speed: 20
    beach:
      frames: 3
      animation_speed: 20
    hand:
      frames: 3
      animation_speed: 20
  width: 69
  height: 94
  spacing: 20
  route: assets/cards/
  extension: .png
ui:
  elements: [icon, arrow]
  arrow_size: 25
  route: assets/ui/
  extension: .png
animation:
  blink_speed: 20
default_user_settings:
  background: 1
  card_back: cross_hatch
  game: 1


